pschachte/wybe

- .github/workflows/macos.yml
- .github/workflows/ubuntu.yml
The macOS one is disabled due to the slowness. The ubuntu one works pretty good (It could be better since there is a ~10 mins overhead of stack building dependencies). 
Without any addtional settings, this CI won't  affect current workflow at all. It simply attachs the CI results to related commits\PRs on the web interface. We can talk about adding the CI check to the workflow during the meeting this week.
> Add Github Actions for running tests.

- src/AST.hs
- src/Builder.hs
- src/Emit.hs
- src/ObjectInterface.hs
- wybe.cabal
Fix #13 
1. Make [extractLPVMDataLinux] to be read-only.
2. Use a clean tmpDir for each build. (Currently the wybe compiler reuses tmp files, so if the previous build used `sudo` and the next build doesn't, then there will be a permission issue.)
> Fix issue #13

- stack.yaml
I am not sure if this is appropriate. The current haskell version (lts-11.11 GHC 8.2.2) seems to be a bit too old. The problem for me is that [Haskell-Ide-Engine](https://github.com/haskell/haskell-ide-engine) has dropped support of that version.
The lts-12.26 seems to be the newest one without upgrading any packages.
> Bump haskell to lts-12.26 (GHC 8.4.4)

- .github/workflows/ubuntu.yml
The CI currently takes about 9 mins on installing and building dependencies of wybe. 
This update is aim to cache the folder used by haskell stack so we can reduce that time to ~1min (after the first run, the time is used for loading and untaring the cache file).
Tested using my own repo.
> Improve ci by caching haskell stack

- src/AST.hs
- src/AliasAnalysis.hs
- src/Transform.hs
- src/Util.hs
- test-cases/final-dump/alias_type4.exp
This PR is a part of #31.
This PR introduces a better way of handling parameters in alias analysis, so we can have a preciser analysis and more optimize opportunities.
In this approach, we consider a parameter as two things, a normal variable and a thing that the variable is (or maybe) alias to outside the procedure scpoe. More detail can be found at around line 37 in `AST.hs`.
> Implement a better way of handling parameters in alias analysis.

- src/AST.hs
- src/AliasAnalysis.hs
- src/Builder.hs
- src/Options.hs
- src/Transform.hs
- test-cases/final-dump/alias_cyclic.exp
- test-cases/final-dump/alias_m.exp
- test-cases/final-dump/alias_mbar.exp
- test-cases/final-dump/alias_mfoo.exp
- test-cases/final-dump/alias_scc_proc.exp
- test-cases/final-dump/alias_type4.exp
- test-cases/final-dump/multi_specz.exp
- test-cases/final-dump/multi_specz_cyclic_exe.exp
- test-cases/final-dump/multi_specz_reverse.exp
- test-cases/final-dump/type_list.exp
This PR is part of #31.
It includes:
1. **A bug fix.**
If a variable is used more than once in a proc call (such as `foo(x, !x)`), then that variable (`x`) should be considered as aliased. The previous code handles this case incorrectly.
2. **Add a new flag `--no-multi-specz` for disabling multiple specialization.**
3. **Prints out lpvm code of multiple specialization versions in FinalDump.**
> Bug fix and small enhancement in multiple specialization

- WYBE.md
Fixed missing `|` between test statements in `WYBE.md`
> Fixed if statement example in WYBE.md

- src/Codegen.hs
- src/Config.hs
- src/Emit.hs
Related issue: #60 
Note that I didn't put all platform-specific things in `Config.hs`, because I don't think they fit the context of config. You can find all of them (including previous ones) by searching usages of `buildOS`.
> Supporting link-time dead code elimination on Linux

- src/AST.hs
- src/Builder.hs
- src/Callers.hs
- src/Clause.hs
- src/Resources.hs
- src/Transform.hs
- src/Types.hs
- test-cases/final-dump/multi_specz.exp
- test-cases/final-dump/multi_specz.wybe
#31 
The main cause is that `fixpointProcessSCC` assume the processor will reach a fixpoint if there is only one mod in the SCC and the processor of the top-down pass doesn't guarantee that.
This PR fix it with a more precise processor which uses `getSccProcs`.
This PR also makes the transform to use the `expandRequiredSpeczVersionsByProcVersion` instead of recomputing it using the aliasMap. So it will be easier to add other multiple specialization and heuristic for selecting specialization.
> Fix a bug where the top-down pass may not reach a fixpoint && some improvements.

- wybelibs/cbits.c
#98 
According to: https://en.cppreference.com/w/c/types/integer
> Fix bitwidth warning compiling cbits.c. #98

- src/Expansion.hs
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/complex/testcase_multi_specz.py
Related issue: #103 
Yet another bug that could be caught by a linter that can identify defined but not used variables.
I'll look into Haskell linter later.
> Fix a bug in assigning CallSiteID.

- src/AST.hs
Fixes a compile warning of an incomplete pattern for `showStmt`.
```
warning: [-Wincomplete-patterns]
Pattern match(es) are non-exhaustive
In an equation for ‘showStmt’: Patterns not matched: _ Fail
|
3132 | showStmt _ (ProcCall maybeMod name procID detism resourceful args) =
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
> Added missing `showStmt` pattern

- src/Builder.hs
- src/Config.hs
- src/Emit.hs
- src/Util.hs
By the default install config, wybemk doesn't have write permissions on object files of the stdlib. However, the multiple specialization framework needs to update those file. So now we have a problem #130.
This PR introduces "local cache file": if wybemk tries to write to a file that it doesn't have write permission, it will create a cache file under `~/.wybe/cache` and uses it instead. It also records the hash of the original file so the cache file will become invalid once the origincal file has changed. The whole thing is transparent to most parts of the compiler.
> Introduce local cache file which allows multiple specialization on read-only libs

- src/Scanner.hs
Example program that fails to parse:
```
!println("Wominjeka!")
#oops!
```
(with no terminal new line)
Output before fix:
```sh
% wybemk test
test.wybe:2:1: Syntax error: unexpected Unterminated comment begins here
expecting simple expression
```
> fix for single-line comment at eof not parsing

- src/Blocks.hs
- src/Types.hs
- test-cases/complex/exp/testcase_multi_specz-drone.exp
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/final-dump/anon_field_variable.exp
- test-cases/final-dump/generic_use.exp
- test-cases/final-dump/main_hello.exp
- test-cases/final-dump/stmt_for.exp
- test-cases/final-dump/type_generics.exp
- test-cases/final-dump/unbranch_bug.exp
This reverts some changes made in the fix for #149 
- types correspond to the callee types, again
- argument types are coerced into parameter types in codegen
> Revert some changes for fix for #149

- src/Resources.hs
- test-cases/final-dump/resource_tmp_vars.exp
- test-cases/final-dump/resource_tmp_vars.wybe
This fixes #209 
- the process of transforming resources into arguments is now handled with a `StateT`, with the state storing information about tmp variables 
- additional test case for #209
> Refactored Resources

- src/ASTShow.hs
- src/Builder.hs
- src/Emit.hs
- src/Options.hs
Can be turned on via the `--dump-opt-llvm` flag, dumping only when FinalDump is logged.
Manually checking a few instances of what's dumped, we may close some issues, such as #207, as the unused declarations are removed in the LLVM optimisation passes
Some issues, such as #186, should not be closed. Perhaps we should curate our own set of LLVM passes that includes, amongst others, `-constmerge`
> Added option to dump optimised LLVM code

- src/AST.hs
- src/Resources.hs
- src/Unique.hs
- test-cases/final-dump/io_flow_error.exp
- test-cases/final-dump/io_flow_error.wybe
- test-cases/final-dump/resource_tmp_vars.exp
- test-cases/final-dump/stmt_for.exp
- test-cases/final-dump/stmt_for.wybe
- test-cases/final-dump/top_level_use.exp
- test-cases/final-dump/use_resource.exp
- wybelibs/wybe/io.wybe
- wybelibs/wybe/phantom.wybe
Make test (and failure) procs with unique arguments/resources illegal.
Make assignment to unique variables/resources in a test or failure context illegal.
Closes issue #223.
> Uniqueness improvements

- src/Optimise.hs
- test-cases/complex/exp/testcase_multi_specz-drone.exp
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/final-dump/alias_cyclic.exp
- test-cases/final-dump/alias_data.exp
- test-cases/final-dump/alias_multifunc4.exp
- test-cases/final-dump/assert_error.exp
- test-cases/final-dump/bug228-okay.exp
- test-cases/final-dump/higher_order_resources.exp
- test-cases/final-dump/main_hello.exp
- test-cases/final-dump/multi_out.exp
- test-cases/final-dump/person5.exp
- test-cases/final-dump/purity_warning.exp
- test-cases/final-dump/resource_rollback.exp
- test-cases/final-dump/resource_tmp_vars.exp
- test-cases/final-dump/stmt_nop.exp
- test-cases/final-dump/terminal_ok.exp
- test-cases/final-dump/unbranch_bug.exp
This PR add the ability to change the interface of a proc and all calls to the proc have more restricted GlobalFlows if we can infer that some flow is unneeded.
For instance, we may have remove through optimisation all writes to a global in a proc. We can then safely remove the outwards flow of the global from the interface of the proc.
> Added GlobalFlow inference

- src/Resources.hs
- test-cases/final-dump/break_in_loop_in_do.exp
- test-cases/final-dump/break_in_loop_in_do.wybe
> Correctly restore global variables when breaking inside a `use` block in a loop

- src/Types.hs
- test-cases/final-dump/caret.exp
- test-cases/final-dump/failure_in_cond_test.exp
- test-cases/final-dump/failure_in_cond_test.wybe
This fixes issue #250 
In the case a condition is guaranteed to fail, we used to remove the cond, but this was erroneous in a `test` proc because the condition now causes failure of the whole proc. We also cannot remove the condition because it may have side-effects. Instead, we still generate the cond, but have nothing in the "then" branch. 
A relevant test case exists for this.
> Fix for bug #250

- src/BodyBuilder.hs
- test-cases/final-dump/bug214.exp
- test-cases/final-dump/dead_cell_size.exp
- test-cases/final-dump/string.exp
In my own musings, I decided to see if I had correctly performed the common subexpression optimisation correctly for higher order. To my surprise, I think that the current common subexpression optimisation isnt done as well as it could be--the `CallSiteID` is something that should be canonicalised away, as it is not relevant in finding a common subexpression.
This PR fixes that. Test cases have been updated to reflect these changes, and it shows some cases where this optimisation wasnt done.
Minor tweaks are also in the PR, to flesh out the logging messages and attach more position information to the CSE moves.
> Improved common subexpr optimisation; minor tweaks

- src/Emit.hs
Closes https://github.com/pschachte/wybe/issues/266
I didn't see `withModule` originally, so have now refactored to make use of it.
Side note: it looks like my editor likes to automatically trim trailing whitespace. Before I put up a PR to trim trailing whitespace in all the other source files too, is there some significance to the current trailing whitespace that I'm missing?
> respect --no-llvm-opt flag

- WYBE.md
- src/AST.hs
- src/ASTShow.hs
- src/Blocks.hs
- src/BodyBuilder.hs
- src/Builder.hs
- src/Callers.hs
- src/Clause.hs
- src/Codegen.hs
- src/Config.hs
- src/Emit.hs
- src/Expansion.hs
- src/Flatten.hs
- src/Macho.hs
- src/Normalise.hs
- src/ObjectInterface.hs
- src/Optimise.hs
- src/Options.hs
- src/Parser.hs
- src/README.md
- src/Resources.hs
- src/Scanner.hs
- src/Snippets.hs
- src/Transform.hs
- src/Types.hs
- src/Unbranch.hs
- src/Unique.hs
- src/UnivSet.hs
- src/Util.hs
I'm hoping this might make future PRs simpler by getting rid of inconsistent trailing whitespace.
To create this diff, I went and ran "trim trailing whitespace" in my editor for each file in `src/`.
I wonder for the future, whether adopting some sort of autoformatter / linter might make this easier? I've used `hlint` before, but I don't think it does whitespace/formatting stuff.
> remove trailing whitespace + rerun make src/README.md

- src/Types.hs
- test-cases/final-dump/higher_order_sort.exp
- test-cases/final-dump/higher_order_sort.wybe
As the title says. 
Assumptions I made about the AST for type checking are only true for the first iteration of type checking an SCC, i.e., there are no higher order calls to type check. This is wrong on the second/higher iteration when reaching a fixed point (something something higher order)
A test case has also been added that caught this bug.
> Fixed type checking of untyped, higher order, recursive functions' 

- src/Types.hs
A bug I made allowed partial applications to have an inferred resourceful higher-order type if there were in *and* out flowing resources for the proc. This fixes that, as it should be in *or* out flowing.
> Fixed resourcefulness of partial applications

- src/Blocks.hs
- src/Codegen.hs
- src/Transform.hs
- test-cases/execution-test.sh
- test-cases/final-dump-test.sh
I haven't had a chance to discuss this one yet, so I'd be open to any feedback (maybe there's something I'm missing why it's done the way it is?)
- When implementing new LPVM instructions, I accidentally introduced a couple of bugs by falsely claiming an operand was of type `x` (by writing `assign name op x`), when the operand was actually of a different type `y`.
- I learned that each LLVM `Operand` has a type, which can be retrieved with `typeOf operand`
Thus, I thought it might make sense to use the LLVM type of the operand itself, rather than passing in an extra argument. This also simplifies `doCast` and `consCast`.
I believe this code change shouldn't break any of the tests / final dumps. I'd be keen to hear what you think.
I also have an extra commit …
> Infer more LLVM types during codegen, remove some unused code

- src/BodyBuilder.hs
- test-cases/final-dump/out_global_overwritten.exp
- test-cases/final-dump/out_global_overwritten.wybe
- test-cases/final-dump/out_only_global_flow.exp
- test-cases/final-dump/out_only_global_flow.wybe
As the title says. This strengthens the definition of neededness in terms of global flows
i.e., assuming a prim is pure and has no regular *needed* outputs, a prim is needed iff the outwards global flows of the prim are not overwritten by some later prim
```
resource res:int
def {noinline} out use ?res { ?res = 11 }
use res in {
?res = 10
!out
!println(res)
}
```
The `?res = 10` assignment is redundant
```
resource res:int
def {noinline} out use ?res { ?res = 11 }
use res in { 
!out
?res = 10 
!println(res)
}
```
No global flows for `res` occur in the top-level, as the `!out` call can now be omitted. 
This applies to all prims where the outwards global flows are overwritten later on.
> Improved backwards analysis with global flows

- src/Flatten.hs
- src/Unbranch.hs
- test-cases/final-dump/loop_terminators.exp
- test-cases/final-dump/loop_terminators.wybe
As the title says. 
Fixes #292 
The new test case raises a few questions though--
An infinite loop as I have used here doesn't look right. The looping procs should not be empty, but recursive calls to themselves. The issue though, is there is no *un-needed* outputs, so the recursive call is removed. I suspect `terminal` procs shouldn't be removed and should essentially always needed.
But when I try to declare them as terminal, the compiler says that the determinism is wrong. Perhaps I should raise another issue
> Delay addition of `next` statement form Flatten to Unbranching

- src/Optimise.hs
This PR doesn't fix any bugs. Expansion performs the same analysis that this refinements does, however this refinement ensures that the same "killing" of inwards flows can occur in Optimise also.
> Refine the inference of global flows

- src/LastCallAnalysis.hs
- src/Options.hs
Just like there is a `--no-multi-specz` switch which disables multiple specialization, I have added a `--no-tcmc`  switch which disables the tail-call-modulo-construction optimization.
I realise this may end up being a bit of a rabbit-hole if we keep adding switches for every possible optimization the Wybe compiler might perform, but I guess it is quite similar to how e.g.: clang has a bunch of `-f` flags to control each possible optimization (https://clang.llvm.org/docs/ClangCommandLineReference.html#target-independent-compilation-options). Perhaps there is a different naming convention all of these flags should use? For now I have stuck with `--no-xyz`.
There was one trick with the implementation: we want to keep calling `fixupCallsInProc` even if the optimization is disabled, since we …
> add --no-tcmc switch

- src/Parser.hs
- test-cases/final-dump/unbranch_bug.exp
- wybelibs/wybe/array.wybe
- wybelibs/wybe/float.wybe
- wybelibs/wybe/list.wybe
- wybelibs/wybe/string.wybe
This PR primarily adds more functionality to the array type, allowing for updates and creation.
Other changes include:
* minor tweaks of the docs in the stdlib
* a fix to a parser "bug" that I encountered when testing this. E.g., something like:
```
?a = array([1,2,3])
if { !a[1] = 10 :: pass }
```
was parsed as
```
?a = array([1,2,3])
if { `[]`(a, 1) = 10 :: pass }
```
instead of the intended
```
?a = array([1,2,3])
if { (!a)[1] = 10 :: pass }
```
Funnily enough, the erroneous parse was actually type correct, so it compiled just fine
> Improve `array` type

- src/AST.hs
- src/Blocks.hs
- src/Types.hs
- test-cases/final-dump/higher_order_arity_error.exp
- test-cases/final-dump/higher_order_arity_error.wybe
- test-cases/final-dump/higher_order_phantom.exp
- test-cases/final-dump/higher_order_phantom.wybe
Previously, a higher order call with a phantom-typed *variable* argument was called, there was an error as phantoms aren't assigned in LLVM codegen. This PR fixes that, by replacing the phantoms with `undef`. Such higher order calls can also be omitted if it only produces phantoms as those values are never used in LLVM.
In testing, I accidentally had an arity error in one of my higher order calls, and in fixing this, I was lead to me discover a bug in the determinism checking of higher order calls. This PR also fixes that.
> Fixed higher order with phantom arguments & higher order determinism checks

- src/AST.hs
- src/Flatten.hs
- src/Parser.hs
- src/Types.hs
- src/Unique.hs
- test-cases/final-dump/bang_expression_error.exp
- test-cases/final-dump/bang_expression_error.wybe
This code
```
def my_map(f:{resource}(T,?T), lst:list(T)):list(T) =
if {
lst = [?h|?t] :: [h2 | !my_map(f, t)] where { !f(h, ?h2) }
|   else          :: []
}
```
now compiles fine. Note the `!` before the `my_map` call.
The call to `f` occurs before the recursive call, which is what I think we want to happen.
> Fix for #342

- src/AST.hs
- src/Builder.hs
- src/Resources.hs
- src/Types.hs
- src/Unbranch.hs
- src/Unique.hs
- test-cases/final-dump/break_in_loop_in_do.exp
- test-cases/final-dump/higher_order_resources.exp
- test-cases/final-dump/resource_tmp_vars.exp
This PR unifies the resource transformation passes that transform resources into params/args and then globals. Uniqueness checking interfered with this before, however, now I have changed that pass to handle pre-resource transformation code by using the resources found in a proc's prototype instead of the parameterised resources.
This unification isn't strictly necessary, however it does simplify the resource module greatly.
> Unified resource transformations

- src/Flatten.hs
- test-cases/final-dump/bug_var_def.exp
- test-cases/final-dump/bug_var_def.wybe
Previously the added test case raised this error:
```
Error detected during type checking of module(s) tmp
Higher order call to tmp#0 in module top-level code has a type/flow error.
```
This PR fixes that
> Fix bug where tmp vars were not defined, leading to flattening issues

- src/Normalise.hs
- test-cases/complex/exp/testcase_multi_specz-drone.exp
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/final-dump/main_hello.exp
- test-cases/final-dump/parametric_repn.exp
- test-cases/final-dump/parametric_repn.wybe
- wybelibs/command_line.wybe
- wybelibs/wybe/array.wybe
Type parameters for representation types are not meaningful, since the representation can't refer to the type variable.
This was only possible with `type` declarations (not with `representation` declarations) anyway.
Also remove the type parameter to the `raw_array` type defined in the `wybe.array` library.
>  Forbid type parameters for types defined by representation.

- src/AST.hs
Previously we have
https://github.com/pschachte/wybe/blob/6fe5353e751051e4e1292b644f379980ea484735/src/AST.hs#L2950-L2954
but this would fail type-checking with the following message
```
Error detected during type checking of module(s) <module>
Type of 1 incompatible with wybe.bool
```
> Fixed `seqToStmt` on an empty list to return `Nop`

- src/AST.hs
- test-cases/final-dump/current_module_alias_type_args.exp
- test-cases/final-dump/current_module_alias_type_args.wybe
> Fixed `lookupType'` not resolving type arguments when a current module alias is used

- src/AST.hs
- src/Flatten.hs
- src/Types.hs
- test-cases/final-dump/alias_recursion2.exp
- test-cases/final-dump/card.wybe
- test-cases/final-dump/case_detism.exp
- test-cases/final-dump/case_detism.wybe
- test-cases/final-dump/detism_error.exp
- test-cases/final-dump/error_mode.exp
- test-cases/final-dump/error_mode2.exp
- wybelibs/wybe/char.wybe
- wybelibs/wybe/control.wybe
- wybelibs/wybe/count.wybe
- wybelibs/wybe/string.wybe
Introduce `shouldnt` proc and function to report an error that shouldn't happen. Fixes #433.
>  Fix determinism analysis of case statements and expressions

- src/AST.hs
- src/Clause.hs
- src/Flatten.hs
- src/Parser.hs
- src/Types.hs
- src/Unique.hs
- test-cases/final-dump/cond_expr_no_else.exp
- test-cases/final-dump/cond_expr_no_else.wybe
- test-cases/final-dump/cond_expr_no_else_err1.exp
- test-cases/final-dump/cond_expr_no_else_err1.wybe
- test-cases/final-dump/cond_expr_no_else_err2.exp
- test-cases/final-dump/cond_expr_no_else_err2.wybe
This makes the expression semidet, so it can only be done in test/partial contexts.
added test cases.
>  Allow conditional and case expressions to omit the else branch

- src/Types.hs
If there's an unresolved residue after type checking, only report the first one to avoid overwhelming error messages.
> Only report the first ambiguous overloading error

- WYBE.md
- src/AST.hs
- src/Builder.hs
- src/Flatten.hs
- src/Normalise.hs
- src/Parser.hs
- src/Resources.hs
- src/Types.hs
- src/Unbranch.hs
- src/Unique.hs
- test-cases/final-dump/foreign_def.exp
- test-cases/final-dump/foreign_def.wybe
- test-cases/final-dump/foreign_def_errors.exp
- test-cases/final-dump/foreign_def_errors.wybe
- test-cases/final-dump/foreign_def_unordered.exp
- test-cases/final-dump/foreign_def_unordered.wybe
> Add foreign proc def

- src/AST.hs
- src/ASTShow.hs
- src/Config.hs
- src/Options.hs
- src/wybemk.hs
> Add --llc-path and --log-file options
