- src/AST.hs
- src/AliasAnalysis.hs
- src/BinaryFactory.hs
- src/Clause.hs
- src/Expansion.hs
- src/Transform.hs
- src/Util.hs
- test-cases/final-dump/alias_fork1.exp
- wybe.cabal
This PR comtains fix for #21 and #25 .
For #21 , changes can be found here https://github.com/pschachte/wybe/commit/0a6393a984c32471588d593416266b62ba061d5f
For #25, this is only a quick and naive fix (replace it with a navie disjoint set), please don't close that issue.
> Fix Alias Analysis

- src/Builder.hs
Fix issue #47.
I believe the issue here is that the `buildModuleIfNeeded ` consider the dependency "tree" as a DAG and doesn't handle cycle properly.
> Fix issue #47

- src/Builder.hs
- wybelibs/cbits.c
More detail can be found here: #59
> Mitigate performance issue in GC (workaround) && Prevent optimiser to remove the call to gc_init

- WYBE.md
> fix invalid sample in WYBE.md

- src/AST.hs
- src/ASTShow.hs
- src/BinaryFactory.hs
- src/Builder.hs
> Fix #66 by using the hash of module's public interface.

- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/complex/testcase_multi_specz.py
- test-cases/complex/utils.py
This case is for multiple specialization #31.
It contains a int_list lib which supports many operations similar to python's list.
I think the multiple specialization works pretty well expect for one case: the `range` function.
I'd like to discuss it during today's meeting.
> Add complex test case: int_list.

- test-cases/complex/exp/testcase_multi_specz-drone.exp
- test-cases/complex/testcase_multi_specz.py
- test-cases/complex/utils.py
This case is for mutiple specialization and CTGC with destructive mutate instructions.
> Add complex test case: drone.

- src/AliasAnalysis.hs
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/complex/testcase_multi_specz.py
> Fix an incorrect behavior of aliasMap.

- src/AliasAnalysis.hs
An attempt to fix #87 but it doesn't work, because in that case, the recursive call is using that param.
However, I think the change of this PR is still needed, it will work once we make the unneeded param analysis a bit smarter.
> Ignore unneeded param in AliasAnalysis.

- .github/workflows/ubuntu.yml
- Makefile
The current `make install` is broken on both ubuntu and macos (zsh).
This RP fixes that and makes the CI to test `make install`.
> Fix make install command.

- src/Emit.hs
As described in #49, this pull request fix the issue by enabling LLVM optimisation pass manager on executable.
A similar commit 1d45ba686a had been made by @pschachte to enable the pass manager on object file, but inconsistency between `makeWrappedBCFile` and `makeWrappedObjFile`  was introduced by 1d45ba686a on 17 Oct 2020. #49 was reported on 6 May 2020, well before the commit. 
What we are doing seems like a band-aid to the problem instead of fixing the issue behind it, but at least this pull request will make the compiler use LLVM optimized code to generate the executable instead of unoptimized code.
> Fix inconsistency between .ll and executable 

- src/Callers.hs
- src/Transform.hs
> Fix multiple specialization bug #134

- Makefile
- WYBE.md
- src/AST.hs
- src/ASTShow.hs
- src/Normalise.hs
- src/README.md
- src/Resources.hs
- src/Snippets.hs
- src/Types.hs
- test-cases/execution-test.sh
- test-cases/final-dump-test.sh
- test-cases/final-dump/resource_error2.exp
- test-cases/final-dump/resource_error2.wybe
- test-cases/final-dump/specials.exp
- test-cases/final-dump/specials.wybe
- test-cases/final-dump/specials_one_module.exp
- test-cases/final-dump/specials_one_module.wybe
- test-cases/final-dump/specials_use.exp
- test-cases/final-dump/specials_use.wybe
Implement "special" resources.  Closes #136.
> Special resources

- src/AliasAnalysis.hs
- test-cases/final-dump/alloc_args.exp
- test-cases/final-dump/alloc_args.wybe
This fix changes code related to dead cell reuse (cc @CaviarChen )
> Fix for alloc args (#145)

- WYBE.md
- src/Config.hs
- src/Normalise.hs
- src/Parser.hs
- test-cases/final-dump/anon_field.exp
- test-cases/final-dump/anon_field.wybe
- test-cases/final-dump/ctor_char.exp
- test-cases/final-dump/ctor_char.wybe
- test-cases/final-dump/ctor_char2.exp
- test-cases/final-dump/ctor_char2.wybe
Also removed normalization to create accessors/mutators for said fields
> Allowed constructors to omit field names (#153)

- src/Parser.hs
- test-cases/final-dump/anon_field_variable.exp
- test-cases/final-dump/anon_field_variable.wybe
> Fixed type variables in anonymous constructor fields

- src/Parser.hs
> Fixed position of leading tokens when parsing

- src/AST.hs
- src/Flatten.hs
- src/Parser.hs
- test-cases/final-dump/det_for.exp
- test-cases/final-dump/det_for.wybe
- test-cases/final-dump/int_sequence.exp
- test-cases/final-dump/stmt_for.exp
- test-cases/final-dump/string.exp
- test-cases/final-dump/unbound_after_for.exp
- test-cases/final-dump/unbound_after_for.wybe
- test-cases/final-dump/unbranch_bug.exp
> Refactored for loop flattening

- src/Flatten.hs
- test-cases/final-dump/anon_field_variable.exp
- test-cases/final-dump/dont_care_constraint.exp
- test-cases/final-dump/dont_care_constraint.wybe
> Fixed issues regarding `_`

- test-cases/complex/exp/testcase_multi_specz-drone.exp
- test-cases/complex/exp/testcase_multi_specz-int_list.exp
- test-cases/execution/string.wybe
- test-cases/final-dump/main_hello.exp
- test-cases/final-dump/string.exp
- test-cases/final-dump/string.wybe
- wybelibs/command_line.wybe
- wybelibs/logging.wybe
- wybelibs/wybe/array.wybe
- wybelibs/wybe/c_string.wybe
- wybelibs/wybe/char.wybe
- wybelibs/wybe/list.wybe
- wybelibs/wybe/string.wybe
This PR adds list indexing to the stdlib and cleans up the code a little.
> Stdlib additions

- src/Scanner.hs
- wybelibs/wybe/char.wybe
- wybelibs/wybe/string.wybe
This partially adds the functionality of #230
> Added support for the null character constant

- src/AST.hs
- src/Flatten.hs
- src/Types.hs
- test-cases/final-dump/alias_recursion3.exp
- test-cases/final-dump/bug228-type.exp
- test-cases/final-dump/bug228-type.wybe
- test-cases/final-dump/constant_type_constraint_error.exp
- test-cases/final-dump/in_before_out.exp
- test-cases/final-dump/incompatible_generics.exp
- test-cases/final-dump/incompatible_generics_2.exp
- test-cases/final-dump/type_change.exp
- test-cases/final-dump/use_before_def.exp
These changes are mostly from @pschachte's #244 fix, and some light cosmetic changes.
> Final #228 changes

- WYBE.md
- src/Emit.hs
- src/Options.hs
> Add -O flag

- src/AST.hs
- src/Blocks.hs
- src/BodyBuilder.hs
- src/Callers.hs
- src/Clause.hs
- src/Expansion.hs
- src/Flatten.hs
- src/Resources.hs
- src/Types.hs
- src/Unbranch.hs
- src/Unique.hs
- test-cases/final-dump/higher_order_refs.exp
- test-cases/final-dump/uneeded_closure_args.exp
- test-cases/final-dump/uneeded_closure_args.wybe
As the title says. 
Also, ProcRef has been renamed to Closure as this better reflects what the structure is
> Replace unneeded closure arguments with unneeded value

- src/Builder.hs
- src/Emit.hs
- src/LastCallAnalysis.hs
- src/Options.hs
- src/Transform.hs
- test-cases/complex/utils.py
> Refactored Optimisation flags

- src/Types.hs
- test-cases/final-dump/bad_assign.exp
- test-cases/final-dump/bad_assign.wybe
A relevant test-case has been made with a better error message shown.
> Fix for #310

- src/AST.hs
- src/Types.hs
- test-cases/final-dump/higher_order_flow_error.exp
- test-cases/final-dump/higher_order_flow_error.wybe
> Corrected checking of flows in higher order calls

- test-cases/final-dump/higher_order_append.exp
- test-cases/final-dump/higher_order_append.wybe
- test-cases/final-dump/higher_order_resources.exp
- wybelibs/wybe/list.wybe
* Added `empty` test for lists
* Added some short documentation for the list type
* Re-ordered `list.print` arguments, regarding discussion in #304 
**Note: merging this will lead to build errors for other PRs**
> Stdlib additions/tweaks

- test-cases/final-dump/higher_order_resources.exp
- wybelibs/wybe/array.wybe
- wybelibs/wybe/list.wybe
- wybelibs/wybe/machine_word.wybe
- wybelibs/wybe/range.wybe
- wybelibs/wybe/string.wybe
Also added a `word_size` constant, slight changes to docs and a minor change to `range`
> Added conversion between lists and arrays

- src/Blocks.hs
- test-cases/final-dump/extern_anon_params_a.exp
- test-cases/final-dump/extern_anon_params_a.wybe
- test-cases/final-dump/extern_anon_params_b.exp
- test-cases/final-dump/extern_anon_params_b.wybe
> Fixed LLVM params for external anonymous procs

- src/AST.hs
- src/Normalise.hs
- src/Unique.hs
- test-cases/final-dump/common_fields.exp
- test-cases/final-dump/common_fields.wybe
> Generate more intelligent code where fields are shared between constructors

- src/Options.hs
A small quality of life improvement. If you want to log all but say types, `-lno-types`.
> Improved logging flags to toggle log aspects

- WYBE.md
- src/AST.hs
- src/Flatten.hs
- src/Parser.hs
- src/Unique.hs
- test-cases/final-dump/higher_order_anon.exp
- test-cases/final-dump/higher_order_anon.wybe
- test-cases/final-dump/higher_order_anon_errs.exp
- test-cases/final-dump/higher_order_anon_errs.wybe
Closes #379.
Will cause problems with #377, and either of these branches will have to have `update-exp` ran before merging it. 
The changes should be compatible, though.
> Added anonymous function syntax

- src/Unbranch.hs
- test-cases/final-dump/unbranch_inout.exp
- test-cases/final-dump/unbranch_inout.wybe
> Fix unbranching issue with in-out params that are unused

- src/Builder.hs
- src/Normalise.hs
- src/Snippets.hs
- test-cases/execution/main_topo0.exp
- test-cases/execution/main_topo0.wybe
- test-cases/execution/main_topo1.exp
- test-cases/execution/main_topo1.wybe
- test-cases/execution/main_topo2.exp
- test-cases/execution/main_topo2.wybe
`a.wybe`:
```
pub resource a_res:int = 2:int
```
`b.wybe`:
```
use a  # doesn't matter if it's pub
?b = 0  # anything as long as it's a top-level stmt
```
`c.wybe`:
```
use a,b
?c = 0
```
Running `wybemk c` with the above files would yield the following error message:
```
Error detected during type checking of module(s)
Input resource a_res not available at call to proc
```
The logs reveal that the main executable module imports the module dependencies in a non-topological order (`[b, a, c]` instead of `[a, b, c]`) (credit to @jimbxb):
```
Module 
representation  : (not a type)
public submods  : 
public resources: 
public procs    : 
imports         : use a
use b
use c
use command_line
use wybe
use wybe.array
use wybe.bool
use wybe.c_string
use wybe.char
use wybe.comparison
use …
```
> Fixed executable module importing mod dependencies not in topological order

- src/AST.hs
- src/Normalise.hs
- test-cases/final-dump/badmodname.exp
- test-cases/final-dump/badmodname.wybe
> Disallow `.` character in module/type names

- WYBE.md
- src/Resources.hs
- src/Types.hs
- test-cases/execution/error_expr.exp
- test-cases/execution/error_expr.wybe
- test-cases/final-dump/weird_err_b.wybe
- test-cases/final-dump/weird_err_d.wybe
- wybelibs/wybe/control.wybe
> Add error function

- test-cases/execution/error_expr.exp
- wybelibs/wybe/cbits.c
> Flush output buffer before printing error message

- src/Unbranch.hs
- test-cases/final-dump/undef_bug.exp
- test-cases/final-dump/undef_bug.wybe
> Fix bug setting variable to undef

- src/Unbranch.hs
- test-cases/final-dump/factor_bug.exp
- test-cases/final-dump/factor_bug.wybe
Allow output parameter names to be taken as inputs to factored procs during unbranching.
> Fix bug #390
